### ISSUE TITLE
Add the ability to expand environment variables on the arg parameters

### ISSUE THREAD

**Issue by thomasbellio** [generationtux/brizo#88]
The use case here, is that I want the logger container for paper trail to be defined in my app version in brizo and the command line arguments to be passed to the container are environment dependent for instance in the pod definition for products prod they look like this: 

```
"-d", "logs4.papertrailapp.com", "-p", "32868", "--hostname=prod.payments", "--tls=true", "/etc/logdir/*.log"
``` 
Notice that they are specific to the environment in this case prod I would like the arguments to be able to look something like this: 

```
"-d", "logs4.papertrailapp.com", "-p", "32868", "--hostname=$BRIZO_ENVIRONMENT.payments", "--tls=true", "/etc/logdir/*.log"
``` 
This way when I move versions between environments I am able to just promote the whole version without having to specify new container definitions for each

**Comment by jlaswell** [comment]
We've added story 2405 in Clubhouse for this.

**Comment by jlaswell** [comment]
Closed by https://github.com/generationtux/brizo/pull/95
